### ISSUE TITLE
Release v0.10.0 - Release Candidate due Nov 24th

### ISSUE THREAD

**Issue by hdamker** [camaraproject/QualityOnDemand#235]
**Problem description**

Multiple operators are looking for a release of v0.10.0 to be able to implement it within Q1/2024 (potentially for announcements at MWCB). The main difference of v0.10.0 towards will be the new event structure with CloudEvents as decided and document within the CAMARA Design Guidelines. 

The release candidate for v0.10.0 should be ** created at end of next week (Friday Nov 23rd) ** to have enough time to validate the release candidate by implementing operators and do the actual release of v0.10.0 at latest before year end break.

**Expected action**

The following PRs MUST be included in the release candidate v0.10.0

- [ ] [#216 Extend session duration](https://github.com/camaraproject/QualityOnDemand/pull/216)
- [ ] [#224 Align event notification with CloudEvents spec](https://github.com/camaraproject/QualityOnDemand/pull/224)
- [ ] [#233 Alignment with changes in https://github.com/camaraproject/Template_Lead_Repository on test definitions](https://github.com/camaraproject/QualityOnDemand/pull/233)
- [ ] Yet to be prepared PR with the update of CHANGELOG.md, README.md and the change of the version number within the OAS file from v0.10.0-wip to v0.10.0-rc. The merge commit of this PR will be the tagged as the release candidate.

The following PRs COULD be included within the release candidate if finalized in time

- [ ] [#228 Add GET /sessions endpoint for retrieving all active sessions of authenticated user](https://github.com/camaraproject/QualityOnDemand/pull/228)
- [ ] Yet to be done PR for issue [#230 Single IPv6 addresses within device](https://github.com/camaraproject/QualityOnDemand/issues/230)

**Additional context**

The release candidate will be the starting point for implementations. Release to be expected about 2 or 4 weeks later.
Between release candidate and release only bug fixes and updates of documentation will be done on the API spec. In case of changes to the OAS file there might be second release candidate ("rc2").

**Comment by hdamker** [comment]
Update on status of this issue: 

- #216, #224 and #233 are merged.
- Now waiting for https://github.com/camaraproject/QualityOnDemand/pull/237 as the discussion in #230 has shown that this is needed to correct an implementation issue with the IPv6 address pattern.
- #228 changed back to draft status as the discussion within the issue isn't yet concluded.
